name: artools
description: "A Dart package that provides handy extensions and helper functions, for a smooth and efficient coding experience."
version: 0.0.3+4
homepage: https://github.com/mani53-dev/artools
issue_tracker: https://github.com/mani53-dev/artools/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: