# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Dart
        uses: dart-lang/setup-dart@v2
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Publish to pub.dev
        env:
          PUB_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: dart pub publish --force